server:
  port: 8081
kafka:
  consumer:
    properties:
      bootstrap.servers: localhost:9092
      group.id: aggregator-group
      key.deserializer: org.apache.kafka.common.serialization.VoidDeserializer
      value.deserializer: kafka.deserializer.SensorEventDeserializer

  producer:
    properties:
      bootstrap.servers: localhost:9092
      key.serializer: org.apache.kafka.common.serialization.VoidSerializer
      value.serializer: kafka.serializer.GeneralAvroSerializer