server:
  port: 8082
grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_home
    username: dbuser
    password: 12345
    driverClassName: org.postgresql.Driver

  sql:
    init:
      mode: always

kafka:
  snapshots:
    properties:
      bootstrap.servers: localhost:9092
      group.id: snapshot-analyzer

      key.deserializer: org.apache.kafka.common.serialization.VoidDeserializer
      value.deserializer: kafka.deserializer.SensorsSnapshotDeserializer

  hubs:
    properties:
      bootstrap.servers: localhost:9092
      group.id: hub-analyzer

      key.deserializer: org.apache.kafka.common.serialization.VoidDeserializer
      value.deserializer: kafka.deserializer.HubEventDeserializer